[package]
name = "condenser-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
condenser = { path = "condenser" }
transformers = { path = "transformers" }
regex = "1.5.4"
glob = "0.3.0"
log = "0.4"
env_logger = "0.9.0"
